### PR TITLE
Math-Magicians: Tests

### PR DESCRIPTION
**Pull request by SaeqaSultani**
# Math-Magicians: Tests

## In this pull request we did the followings:
- [x] Set up React Testing Library following the official [documentation](https://testing-library.com/docs/react-testing-library/intro).
- [x] Wrote unit tests for the files operate.js and calculate.js using Jest.
- [x] Create unit tests for all React components:
   - [x] Use Jest snapshots to test the components.
   - [x] Use React Testing Library to simulate user interaction.
- [x] Ran full tests suite using Jest. All tests passed.
- [x] Made sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- [x] Made sure that the project is perfectly working as intended.
- [x] Documented the project professionally.
----
## Collaborators: [Saeqa Sultani](https://github.com/SaeqaSultani/) & [ZikaZaki](https://github.com/ZikaZaki/)

### CODE REVIEW

**Review by victorokoroji — CHANGES_REQUESTED** [review]
Hi @SaeqaSultani, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that has failed linter checks. Kindly fix your linter errors and submit again 👍🏽 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Saeqa & Zack,  

Your project is complete, great job 🥇! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Highlights 👍
- Good unit test coverage with unit tests with React Testing Library
- Nice job for adding snapshots with Jest on unit tests

**You can also consider:**
- Kindly include instructions on how to run your test cases
- Kindly include the details of the co-project contributor
Implementing the above change(s) will make your ReadMe appear more professional.

<br>
Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by rloterh — APPROVED** [review]
Checked

**Review by rloterh — APPROVED** [review]
Checked

**Pull request merged**
